- kube/Dockerfile
> Updating maven version

- kube/build-deploy-image.sh
> updating build deploy script

- .eslintrc.yml
- src/main/content/_assets/css/instance.scss
- src/main/content/_assets/css/kabanero.scss
- src/main/content/_assets/js/home.js
- src/main/content/_assets/js/instance-common.js
- src/main/content/_assets/js/instance.js
- src/main/content/_data/en/en.yml
- src/main/content/index.html
- src/main/content/instance.html
- src/main/java/io/kabanero/KabaneroInstance.java
- src/main/java/io/kabanero/KabaneroInstanceDetails.java
- src/main/java/io/kabanero/KabaneroManager.java
- src/main/java/io/kabanero/KabaneroRepository.java
- src/main/java/io/kubernetes/KabaneroClient.java
- src/main/java/io/kubernetes/KubeKabanero.java
- src/main/java/io/website/Constants.java
Code for multiple kabanero instances
add JSON index file url for Codewind since it doesn't consume .yaml fixes #5 
example of what it will look like with 2 collection maturity's
> reorganize for multiple kab instances

- ci/build.sh
- ci/docker_push.sh
> update build file

- ci/build.sh
- ci/docker_push.sh
exit build scripts on any error
> dash e to ci scripts

- src/test/java/io/kabanero/KabaneroInstanceTest.java
- src/test/java/io/kabanero/KabaneroManagerTest.java
> adding unit testing for backend

- pom.xml
- src/main/java/io/kabanero/KabaneroManager.java
- src/test/java/io/kabanero/KabaneroManagerTest.java
> mock KabaneroClient class and add more tests

- src/test/java/io/kabanero/KabaneroManagerTest.java
> remove old comment

- src/main/content/_assets/css/home.scss
- src/main/content/_data/en/en.yml
- src/main/content/index.html
> updating dev tools modal

- src/main/content/404.html
- src/main/content/_data/en/en.yml
- src/main/content/_includes/doc_header.html
- src/main/content/_includes/end-of-guide.html
- src/main/content/_includes/footer.html
- src/main/content/blog.html
> Updating translation file

- src/main/content/_assets/css/header.scss
- src/main/content/_includes/header.html
- src/main/content/index.html
format logo
remove unneeded classes
remove bum link
> fix some typos and formatting

- .gitignore
- .vscode/tasks.json
add vs code helpful tasks for development
> add vs code tasks

- src/main/content/_assets/css/home.scss
- src/main/content/_assets/js/home.js
- src/main/content/_config.yml
- src/main/content/index.html
> adding back app manager button

- src/test/java/io/kabanero/KabaneroRepositoryTest.java
> Added test for KabaneroRepository class

- .dockerignore
- .travis.yml
- travis/Dockerfile
- travis/docker_run.sh
> adding automated testing for landing page prs

- src/main/content/_assets/css/home.scss
- src/main/content/index.html
> updating grid on homepage

- travis/Dockerfile
> updating travis dockerfile

- src/main/content/_assets/css/guide-card.css
- src/main/content/_assets/css/instance.scss
- src/main/content/index.html
open manage apps link in new tab
fix guide card text overflow
fix first row in instance pane not aligned with first row in tools
> some minor UI fixes

- src/main/java/io/kubernetes/KabaneroClient.java
> tekton moved from kabanero -> tekton-pipelines namespace

- src/main/java/io/kubernetes/KabaneroClient.java
> tekton is in new namespace

- src/main/content/index.html
> adding sidenav js file to index page

- src/main/content/_assets/css/docs.scss
- src/main/content/_assets/js/home.js
- src/main/content/index.html
> fix manage apps for 0.3.0

- scripts/build_jekyll_maven.sh
- scripts/jekyll_serve_dev.sh
- src/main/content/_assets/css/docs.scss
- src/main/content/_assets/js/home.js
- src/main/content/index.html
> Fix doc bullets and manage button and script mkdir

- Dockerfile
- ci/build.sh
- src/main/content/_assets/css/header.scss
- src/main/content/_assets/css/side-bar.scss
- src/main/content/_assets/js/side-bar.js
- src/main/content/_includes/header.html
- src/main/content/_includes/side-bar.html
fix up side bar and pass doc env vars into the docker container
> fix up side bar and docs build

- src/main/content/_includes/header.html
> Fix header image reference to link in config.yml

- src/main/content/_assets/css/guide.scss
- src/main/content/_assets/css/side-bar.scss
- src/main/content/_assets/js/side-bar.js
- src/main/content/_assets/js/toc.js
- src/main/content/_layouts/guide.html
> fixing guide Scrolling issue and firefox toc display

- src/main/content/_assets/js/guide-utils.js
> Remove snap scrolling

- src/main/content/_layouts/guide-multipane.html
> removing  slash from guide multipane

- src/main/content/instance.html
- src/main/java/io/kabanero/instance/KabaneroInstanceDetails.java
- src/main/java/io/kabanero/instance/KabaneroToolManager.java
- src/main/java/io/kubernetes/KabaneroClient.java
- src/main/java/io/website/Constants.java
- src/main/resources/tools.json
> removing unused tools from tool list and fixing bug on instance page 

- README.md
> Change 'landing' to 'console' to fit rebranding

- README.md
> fix oauth file names in readme

- .vscode/tasks.json
- src/main/content/instance.html
> add vs code oauth dev helper and fix link

- .vscode/tasks.json
- src/main/content/_assets/js/instance.js
- src/main/content/instance.html
> hide che unless installed

- src/main/content/_assets/css/collections.scss
- src/main/content/_assets/js/collections.js
- src/main/content/_data/en/en.yml
- src/main/content/collections.html
- src/main/java/io/kabanero/api/restricted/CollectionsEndpoints.java
> adding CLI version to the collections UI

- Dockerfile
- src/main/content/_data/en/en.yml
> fix permissions for social login

- src/main/content/instance.html
> fixing  spelling on instance page

- src/main/java/io/kabanero/api/restricted/CollectionsEndpoints.java
> no need to parse json

- pom.xml
- src/main/content/_assets/css/home.scss
- src/main/content/_assets/css/instance.scss
- src/main/content/_assets/css/stacks.scss
- src/main/content/_assets/js/instance-common.js
- src/main/content/_assets/js/instance.js
- src/main/content/_assets/js/stacks.js
- src/main/content/_data/en/en.yml
- src/main/content/instance.html
- src/main/content/stacks.html
- src/main/java/io/kabanero/api/InstanceEndpoints.java
- src/main/java/io/kabanero/api/restricted/StacksEndpoints.java
- src/main/java/io/kubernetes/KabaneroClient.java
* integrate new CLI service stacks API
* Update UI for stacks
* Make UI dynamic for multiple repositories
> Stacks api

- src/main/content/_assets/css/home.scss
- src/main/content/_assets/js/instance-common.js
- src/main/content/_assets/js/instance.js
- src/main/content/_data/en/en.yml
- src/main/content/index.html
- src/main/content/instance.html
- src/main/content/stacks.html
clean up some UI in regards to CLI output
> final changes

- src/main/content/_data/en/en.yml
- src/main/content/_layouts/guide-markdown.html
- src/main/content/guides.html
> ordering guides by topic and fixing guide markdown sidebar bug

- src/main/content/_assets/js/instance.js
> use proper field for stack repo URLs

- src/main/content/_assets/css/end-of-guide.scss
- src/main/content/_assets/css/guide.scss
- src/main/content/_assets/css/toc.scss
- src/main/content/_data/en/en.yml
- src/main/content/_includes/end-of-guide.html
- src/main/content/_layouts/guide-markdown.html
- src/main/content/_layouts/guide.html
> fix up guides

- src/main/content/_assets/js/instance.js
- src/main/content/_data/en/en.yml
- src/main/content/instance.html
- src/main/content/stacks.html
- src/main/java/io/kubernetes/KabaneroClient.java
- src/main/java/io/kubernetes/Route.java
- src/main/java/io/website/Constants.java
- src/main/resources/tools.json
replace che with codeready
closes #160
> add codeready tile

- src/main/content/_assets/js/instance.js
- src/main/content/instance.html
- src/main/java/io/kubernetes/KabaneroClient.java
> regex for route urls always

- src/main/content/_assets/js/instance.js
> handle case where there are no stacks

- Gemfile
- scripts/jekyll_serve_dev.sh
- src/main/content/_assets/css/instance.scss
- src/main/content/_assets/js/instance-common.js
- src/main/content/_assets/js/instance.js
- src/main/content/instance.html
- src/main/content/stacks.html
> offset layout of tiles automatically

- src/main/content/_assets/js/instance.js
- src/main/content/_assets/js/stacks.js
- src/main/java/io/kabanero/api/InstanceEndpoints.java
- src/main/java/io/kabanero/api/restricted/GitHubEndpoints.java
Closes #140
Closes #139 
This PR adds API Endpoints to add or remove a given Github user from a given Github team
> API Endpoints to add/remove members from Github teams

- scripts/build_clone_guides.sh
- scripts/build_jekyll_maven.sh
> move skip guides to a file

- src/main/content/_assets/css/instance.scss
- src/main/content/instance.html
> Move stack num

- src/main/java/io/kabanero/tools/KabaneroTool.java
- src/main/java/io/kubernetes/KabaneroClient.java
- src/main/java/io/kubernetes/Route.java
- src/main/resources/tools.json
> Search all routes for tools instead of specific namespaces

- pom.xml
use formal release of 0.8.0 kabanero operator bindings API
> update operator bindings api

- src/main/content/_assets/js/stacks.js
> handle the case where digest policy is not in the CR

- src/main/content/_assets/css/stacks.scss
- src/main/content/_assets/js/stacks.js
- src/main/content/_data/en/en.yml
- src/main/content/stacks.html
- src/test/java/instance/adminViewIT.java
> authentication to the CLI service failure modal

- src/main/content/_config.yml
- src/main/content/_includes/side-bar.html
> external link to kabanero.io docs and guides

- src/main/content/_assets/js/instance-common.js
- src/main/java/io/kabanero/api/restricted/GitHubEndpoints.java
> Updated Github Endpoints to support GHE

- src/main/content/_assets/js/stacks.js
> fix json parsing for cli
